// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.0
// source: item_parser.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text     string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *ParseReq) Reset() {
	*x = ParseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_parser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseReq) ProtoMessage() {}

func (x *ParseReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_parser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseReq.ProtoReflect.Descriptor instead.
func (*ParseReq) Descriptor() ([]byte, []int) {
	return file_item_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ParseReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type KnownItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TypeId   uint32 `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
}

func (x *KnownItem) Reset() {
	*x = KnownItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_parser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnownItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownItem) ProtoMessage() {}

func (x *KnownItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_parser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownItem.ProtoReflect.Descriptor instead.
func (*KnownItem) Descriptor() ([]byte, []int) {
	return file_item_parser_proto_rawDescGZIP(), []int{1}
}

func (x *KnownItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnownItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *KnownItem) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type UnknownItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *UnknownItem) Reset() {
	*x = UnknownItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_parser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnknownItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownItem) ProtoMessage() {}

func (x *UnknownItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_parser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownItem.ProtoReflect.Descriptor instead.
func (*UnknownItem) Descriptor() ([]byte, []int) {
	return file_item_parser_proto_rawDescGZIP(), []int{2}
}

func (x *UnknownItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnknownItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ParseRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnownItems   []*KnownItem   `protobuf:"bytes,1,rep,name=known_items,json=knownItems,proto3" json:"known_items,omitempty"`
	UnknownItems []*UnknownItem `protobuf:"bytes,2,rep,name=unknown_items,json=unknownItems,proto3" json:"unknown_items,omitempty"`
}

func (x *ParseRep) Reset() {
	*x = ParseRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_parser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRep) ProtoMessage() {}

func (x *ParseRep) ProtoReflect() protoreflect.Message {
	mi := &file_item_parser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRep.ProtoReflect.Descriptor instead.
func (*ParseRep) Descriptor() ([]byte, []int) {
	return file_item_parser_proto_rawDescGZIP(), []int{3}
}

func (x *ParseRep) GetKnownItems() []*KnownItem {
	if x != nil {
		return x.KnownItems
	}
	return nil
}

func (x *ParseRep) GetUnknownItems() []*UnknownItem {
	if x != nil {
		return x.UnknownItems
	}
	return nil
}

var File_item_parser_proto protoreflect.FileDescriptor

var file_item_parser_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x22, 0x54, 0x0a, 0x09, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x8e, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x52, 0x65, 0x70, 0x12, 0x3d, 0x0a, 0x0b, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x6e,
	0x6f, 0x77, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x43, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x4f, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x73, 0x65, 0x12,
	0x1b, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_item_parser_proto_rawDescOnce sync.Once
	file_item_parser_proto_rawDescData = file_item_parser_proto_rawDesc
)

func file_item_parser_proto_rawDescGZIP() []byte {
	file_item_parser_proto_rawDescOnce.Do(func() {
		file_item_parser_proto_rawDescData = protoimpl.X.CompressGZIP(file_item_parser_proto_rawDescData)
	})
	return file_item_parser_proto_rawDescData
}

var file_item_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_item_parser_proto_goTypes = []interface{}{
	(*ParseReq)(nil),    // 0: item_parser_proto.ParseReq
	(*KnownItem)(nil),   // 1: item_parser_proto.KnownItem
	(*UnknownItem)(nil), // 2: item_parser_proto.UnknownItem
	(*ParseRep)(nil),    // 3: item_parser_proto.ParseRep
}
var file_item_parser_proto_depIdxs = []int32{
	1, // 0: item_parser_proto.ParseRep.known_items:type_name -> item_parser_proto.KnownItem
	2, // 1: item_parser_proto.ParseRep.unknown_items:type_name -> item_parser_proto.UnknownItem
	0, // 2: item_parser_proto.ItemParser.Parse:input_type -> item_parser_proto.ParseReq
	3, // 3: item_parser_proto.ItemParser.Parse:output_type -> item_parser_proto.ParseRep
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_item_parser_proto_init() }
func file_item_parser_proto_init() {
	if File_item_parser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_item_parser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_parser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnownItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_parser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnknownItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_parser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_item_parser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_parser_proto_goTypes,
		DependencyIndexes: file_item_parser_proto_depIdxs,
		MessageInfos:      file_item_parser_proto_msgTypes,
	}.Build()
	File_item_parser_proto = out.File
	file_item_parser_proto_rawDesc = nil
	file_item_parser_proto_goTypes = nil
	file_item_parser_proto_depIdxs = nil
}
